apiVersion: apps/v1
kind: Deployment
metadata:
  name: copadubo
spec:
  selector:
    matchLabels:
      run: copadubo
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  replicas: 1
  template:
    metadata:
      labels:
        run: copadubo
    spec:
      containers:
        - name: copadubo-view
          image: 130593/copadubo-view:c2611c2
          ports:
            - containerPort: 3000
              protocol: TCP
