apiVersion: apps/v1
kind: Deployment
metadata:
  name: copadubo
spec:
  selector:
    matchLabels:
      run: copadubo
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  replicas: 2
  template:
    metadata:
      labels:
        run: copadubo
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: copadubo-view
          image: 130593/copadubo-view:latest
          imagePullPolicy: "Always"
          ports:
            - containerPort: 3000
              protocol: TCP
